# Generated by Django 4.2.1 on 2023-05-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_count', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
